title: Extrapolating Beyond Suboptimal Demonstrations via Inverse Reinforcement Learning from Observations
authors: Daniel Brown*, Wonjoon Goo*, Prabhat Nagarajan, and Scott Niekum. (* Equal Contribution)
theme: jekyll-theme-cayman
